#!/bin/bash

version="0.4.0-alpha"

tmp_file_name="one_line_tmp.sh"
tmp_file_path=$(pwd)"/"$tmp_file_name

while [[ "$1" ]]; do
    case $1 in 
        "-f" | "--file")
            case $2 in
                "-"*) break ;;
                *)  if [[ -n "$2" ]]; then
                        file_path="$2"
                        if [[ -e $tmp_file_path ]]; then
                            rm -rf $tmp_file_path
                        fi
                        tmp=$(cat $file_path | awk '{$1=$1;print}'); echo -n "$tmp" > $tmp_file_path
                        IFS=$'\n'
                        final=""
                        for LINE in $(cat "$tmp_file_path")
                            do final=$final$LINE" ;"
                                #echo "$LINE"
                        done
                        size=${#final}  ##size of the final line of command
                        rm -rf "$tmp_file_path"
                        #echo "$size"
                        final="${final[@]:13:$size-15}" 
                    fi
                ;;
            esac
        ;;
        "-c" | "--copy")
            case $2 in
                "off") break ;;
                "on" | "-"* | *) 
                    if [[ -n $final ]]; then
                        echo "$final" | pbcopy
                        echo "Code copied to clipboard!!!"
                    fi
                ;;
            esac
        ;;
        "-p" | "--print")
                case $2 in 
                "off") break ;;
                "on" | "-"* | *) 
                    if [[ -n $final ]]; then
                        echo $final
                    fi
                ;;
            esac 
        ;;
        "-v" | "--version")
            echo "Oneliner v"$version
        ;;
        "-s" | "--save")
            echo $final >> oneliner_out.txt
            printf "Output saved to current working directory!!!"
    esac
    shift
done

