
name: BATS testing file

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - 'main'
    workflow_dispatch:

jobs:
    bats:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
            - name: Installing BATS
              run: brew install bats-core
            - name: Running BATS testing file
              run: |
                cd test/
                bats test.bats
            - name: get tmate if job fails
              if: ${{ failure() }}
              uses: mxschmitt/action-tmate@v3
              timeout-minutes: 5
              with:
                detached: true
    shellcheck:
        name: Shellcheck
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run shellcheck
            uses: ludeeus/action-shellcheck@master
            with: './src'

