
name: Makefile test

on:
    push: 
        branches: 
            - 'main'
            - 'master'
    pull_request:
        branches: 
            - 'main'
            - 'master'
    workflow_dispatch:

jobs:
    check-makefile:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: To install make
              run: brew install make
            - name: Compiling Make
              run: make
            - name: Installing app
              run: make install
            - name: Uninstalling app
              run: make uninstall
