
name: Makefile test

on:
    push: 
        branches: 
            - 'main'
            - 'master'
    pull_request:
        branches: 
            - 'main'
            - 'master'
    workflow_dispatch:

jobs:
    check-makefile-on-osx:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: To install make
              run: brew install make
            - name: To install coreutils
              run: brew install coreutils
            - name: Installing app
              run: |
                cd src/
                make install
            - name: Uninstalling app
              run: |
                cd src/
                make uninstall
            - name: get tmate if job fails
              if: ${{ failure() }}
              uses: mxschmitt/action-tmate@v3
              timeout-minutes: 5
              with:
                detached: true
    check-makefile-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: install make
              run: sudo apt-get install -y make
            - name: Installing app
              run: |
                cd src/
                sudo make install
            - name: Uninstalling app
              run: |
                cd src/
                sudo make uninstall
            - name: get tmate if job fails
              if: ${{ failure() }}
              uses: mxschmitt/action-tmate@v3
              timeout-minutes: 5
              with:
                detached: true
