
name: Makefile test

on:
    push: 
        branches: 
            - 'main'
            - 'master'
    pull_request:
        branches: 
            - 'main'
            - 'master'
    workflow_dispatch:

jobs:
    check-makefile-on-osx:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: To install make
              run: brew install make
            - name: To install coreutils
              run: brew install coreutils
            - name: Installing Oneliner
              run: make install
            - name: Uninstalling Oneliner
              run: make uninstall
    check-makefile-on-ubuntu:
        runs-on: ubuntu-latest
        needs: check-makefile-on-osx
        steps:
            - uses: actions/checkout@v4
            - name: install make
              run: sudo apt-get install -y make
            - name: Installing Oneliner
              run: sudo make install
            - name: Uninstalling Oneliner
              run: sudo make uninstall

