name: Comment on PR when test fails.

on:
    pull_request:
      types:
        - opened
      branches:
        - 'main'

jobs:
    pr_comment:
        name: Create Commnent on PR
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
          - name: Create comment on PR
            uses: actions/github-script@v7
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                await github.request("POST /repos/${{ github.repository }}/issues/${{ github.event.number }}/comments", {
                  body: 'Make sure that "BATS & ShellCheck testing" and "Makefile test" workflows pass successfully.',
                });
