
name: Staging deployment

on:
    workflow_run:
        workflows: [Makefile test]
        branches:
            - 'main'
            - 'master'
        types: [completed]
    # push: 
    #     branches:
    #         - 'main'
    #         - 'master'
    workflow_dispatch:

jobs:
    staging_on_osx:
        runs-on: macos-latest
        environment: staging
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v4
            - name: 'Deploy to staging'
              run: |
                cd src/
                make install
                oneliner -v
                oneliner -h
    staging_on_ubuntu:
        runs-on: ubuntu-latest
        environment: staging
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v4
            - name: 'Deploy to staging'
              run: |
                cd src/
                sudo make install
                oneliner -v
                oneliner -h
