
name: Staging deployment

on:
    push: 
        branches:
            - 'main'
            - 'master'
            - 'feat_staging'
    workflow_dispatch:

jobs:
    deployment_to_staging_1:
        runs-on: macos-latest
        environment: staging
        steps:
            - uses: actions/checkout@v3
            - name: 'Deploy to staging'
              run: |
                make install
    deployment_to_staging_2:
        runs-on: macos-latest
        needs: deployment_to_staging_1
        environment: staging
        steps: 
            - uses: actions/checkout@v3
            - name: 'Deploy to staging'
              run: |
                make install
                oneliner -h
    deployment_to_staging_3:
        runs-on: macos-latest
        environment: staging
        needs: deployment_to_staging_2
        steps:
            - uses: actions/checkout@v3
            - name: 'Deploy to staging'
              run: |
                make install
                oneliner -v
                oneliner -h
    deployment_to_staging_4:
      runs-on: macos-latest
      environment: staging
      needs: deployment_to_staging_3
      steps:
          - uses: actions/checkout@v3
          - name: 'Deploy to staging'
            run: |
              make install
              oneliner -h
              oneliner -v
              