
name: Staging deployment

on:
    workflow_run:
        workflows: ["Makefile test"]
        branches: [main, link_jobs]
        types: [completed]
    push: 
        branches:
            - 'main'
            - 'master'
            - 'link_jobs'
    workflow_dispatch:

jobs:
    staging_on_osx:
        runs-on: macos-latest
        environment: staging
        if: ${{ always() }}
        steps:
            - uses: actions/checkout@v3
            - name: 'Deploy to staging'
              run: |
                make install
                oneliner -v
                oneliner -h
    staging_on_ubuntu:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - uses: actions/checkout@v3
            - name: 'Deploy to staging'
              run: |
                sudo make install
                oneliner -v
                oneliner -h
